const { chromium } = require('playwright');
const ts = require('typescript');
const fs = require('node:fs'); const Module = require('node:module'); const assert = require('node:assert/strict');
const m = new Module(require('node:path').join(__dirname,'../lib/finance.ts')); m._compile(ts.transpileModule(fs.readFileSync(require('node:path').join(__dirname,'../lib/finance.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText, require('node:path').join(__dirname,'../lib/finance.ts')); const f=m.exports;
const artists = [{id:1,Employee_ID:'A01',Name:'Asha Kapoor',Role:'Animator'}, {id:2,Employee_ID:'L01',Name:'Rohan Mehta',Role:'Lighting'}, {id:3,Employee_ID:'M01',Name:'Priya Shah',Role:'Lead'}];
const projects = [{id:1,Project_ID:'101_90_plip',Project_title:'The moonlight adventure',Duration:'1 min 30 sec',Status:'Approved',Employee_ID:'A01',Animator:'Asha Kapoor',Lighting_Artist:'Rohan Mehta',Lead:'Priya Shah','Date Approved':f.today(),'Date Assigned':f.today()}, {id:2,Project_ID:'102_60_her',Project_title:'A little everyday magic',Duration:'60 sec',Status:'Approved',Employee_ID:'A01',Animator:'Asha Kapoor','Date Approved':f.today(),'Date Assigned':f.today()}];
let notifications=[];let messageRetries=0;
let wallet = f.emptyWallet();wallet.settings.clientRate=12000;f.syncProjects(wallet,projects,artists);let revision=1;wallet.entries.push({id:'e1',requestId:'receipt1',kind:'receipt',date:f.today(),amount:1000000,note:'First client instalment',projectId:projects[0].Project_ID});
fs.mkdirSync(__dirname+'/artifacts',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH ? {executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH} : {})});const page=await browser.newPage({viewport:{width:1440,height:1100}}); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('AniBlend_user',JSON.stringify({id:'test-manager',email:'test@example.invalid',full_name:'Studio Manager',role:'manager',access_level:'full'})));
 await page.route('**/api/**',async route=>{const req=route.request();let body={};try{body=req.postDataJSON()||{}}catch{};let result={data:[]};if(req.url().endsWith('/api/finance')){if(req.method()==='POST'){assert.equal(body.revision,revision);if(body.action==='draft')wallet.drafts[`${body.month}:${body.employeeId}`]=body.draft;else if(body.action==='mark_paid'){f.settle(wallet,body.employeeId,body.keys,body.month,body.requestId,'settlement-ui',body.cutoff);notifications=[{id:'notice-ui',settlement_id:'settlement-ui',employee_id:'A01',project_id:'102_60_her',status:'failed',last_error:'Mock delivery failure'}];}else if(body.action==='cashout')f.closeCycle(wallet,body.projectIds,body.cutoff,body.requestId,'cycle-ui');else if(body.action==='sync')f.syncProjects(wallet,projects,artists);else if(body.action==='settings')wallet.settings=f.validateSettings(body.settings);else if(body.action==='entry')wallet.entries.push({...body,id:'e2',amount:Math.round(body.amount*100)});else throw Error('Unexpected UI mutation '+body.action);revision++;}result={wallet,revision,projects,artists,notifications,notificationSetupRequired:false};}else if(req.url().endsWith('/api/finance/notifications')){assert.equal(body.action,'retry');messageRetries++;notifications[0].status='sent';notifications[0].last_error=null;result={notifications};}else if(req.url().endsWith('/api/projects'))result={data:body.range?.from>0?[]:projects};else if(req.url().endsWith('/api/animators'))result={data:artists};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(result)});});
 await page.goto((process.env.TEST_BASE_URL || 'http://127.0.0.1:3100') + '/manager');await page.getByRole('button',{name:'Profit Tracker'}).click();await page.getByRole('heading',{name:'Every project. Every rupee.'}).waitFor();
 await page.screenshot({path:__dirname+'/artifacts/wallet-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Rates & settings',exact:true}).click();
 await page.getByLabel('Partner 1 name',{exact:true}).fill('Founder One');await page.getByLabel('Partner 2 name',{exact:true}).fill('Founder Two');await page.getByLabel('Partner 1 share (%)',{exact:true}).fill('60');
 const rateTable=page.getByRole('group',{name:'Client rates / minute',exact:true});await rateTable.getByRole('button',{name:'+ Add rate',exact:true}).click();await page.getByLabel('Client rates / minute code 1',{exact:true}).fill('pt');await page.getByLabel('Client rates / minute amount 1',{exact:true}).fill('8000');
 await page.getByRole('button',{name:'Save rates',exact:true}).click();await page.getByRole('status').waitFor();assert.equal(wallet.settings.partnerOnePercent,60);assert.equal(wallet.settings.clientRates.pt,8000);
 await page.getByRole('button',{name:'Profit overview',exact:true}).click();await page.getByText('Founder One · 60%',{exact:true}).waitFor();
 const profitBefore=f.summarize(wallet,'all').profit;const revenueBefore=f.summarize(wallet,'all').revenue;
 await page.getByRole('button',{name:'Team payouts',exact:true}).click();const member=page.locator('article').filter({has:page.getByRole('heading',{name:'Asha Kapoor',exact:true})});
 await member.getByLabel('Bonus (₹)',{exact:true}).fill('500');await member.getByLabel('Tax withholding (%)').fill('0');await member.getByRole('button',{name:/Save draft/}).click();await page.getByRole('status').waitFor();
 await member.getByRole('button',{name:'Review payment'}).click();await page.getByRole('button',{name:'Mark Paid',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('heading',{name:'Every project. Every rupee.'}).waitFor();
 assert.equal(wallet.settlements.length,1);assert.equal(wallet.settlements[0].tds,0);assert.equal(f.summarize(wallet,'all').revenue,revenueBefore);assert.equal(f.summarize(wallet,'all').profit,profitBefore-50000);assert.equal(f.pending(wallet,f.today().slice(0,7)).filter(o=>o.employeeId==='A01').length,0);
 await page.getByRole('button',{name:'Retry message',exact:true}).click();await page.getByText('✓ Sent',{exact:true}).waitFor();assert.equal(messageRetries,1);assert.equal(wallet.settlements.length,1,'Retry message must never record a second payment');
 await page.getByRole('button',{name:'Wallet history',exact:true}).click();await page.getByText('Asha Kapoor',{exact:true}).waitFor();await page.screenshot({path:__dirname+'/artifacts/wallet-history.png',fullPage:true});
 await page.reload();await page.getByRole('button',{name:'Payout Calculator'}).click();await page.getByRole('heading',{name:'Every project. Every rupee.'}).waitFor();assert.equal(await page.locator('article').filter({has:page.getByRole('heading',{name:'Asha Kapoor',exact:true})}).count(),0);
 await page.getByRole('button',{name:'Profit Tracker'}).click();await page.getByRole('heading',{name:'Every project. Every rupee.'}).waitFor();
 await page.getByLabel('Project payment status').selectOption('current');
 assert.equal(await page.locator('tr').filter({hasText:'102_60_her'}).count(),1,'Mark Paid must keep project in current cycle');
 assert.equal(await page.locator('tr').filter({hasText:'101_90_plip'}).count(),1,'Partly paid project stays current');
 const beforeClose=f.summarize(wallet,'all');
 await page.getByRole('button',{name:/Cashout paid projects/}).click();const dialog=page.getByRole('dialog');
 assert.equal(await dialog.getByText('102_60_her',{exact:true}).count(),1);assert.equal(await dialog.getByText('101_90_plip',{exact:true}).count(),0);
 await dialog.getByRole('button',{name:'Confirm cashout',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(wallet.settlements.length,1,'Cycle cashout must not create another artist payout');assert.equal(wallet.cycles.length,1);assert.deepEqual(f.summarize(wallet,'all'),beforeClose);
 assert.equal(await page.locator('tr').filter({hasText:'102_60_her'}).count(),0,'Paid project leaves current ONLY after Cashout');
 assert.equal(await page.locator('tr').filter({hasText:'101_90_plip'}).count(),1,'Unpaid roles survive Cashout');
 await page.reload();await page.getByRole('button',{name:'Profit Tracker'}).click();await page.getByRole('heading',{name:'Every project. Every rupee.'}).waitFor();
 assert.equal(await page.locator('tr').filter({hasText:'102_60_her'}).count(),0,'Cycle survives refresh');
 await page.getByLabel('Project payment status').selectOption('archived');assert.equal(await page.locator('tr').filter({hasText:'102_60_her'}).count(),1);
 await page.getByRole('button',{name:'Wallet history',exact:true}).click();await page.getByRole('heading',{name:'Cycle cashout history'}).waitFor();
 await page.getByRole('button',{name:'Profit overview',exact:true}).click();await page.getByLabel('Project payment status').selectOption('all');
 const revenueCard=page.locator('div').filter({has:page.locator('span').filter({hasText:/^Lifetime earned revenue$/})}).filter({has:page.locator('small').filter({hasText:'Cashouts never reduce earned revenue'})}).last();
 assert.ok((await revenueCard.textContent()).includes((revenueBefore/100).toLocaleString('en-IN')));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:__dirname+'/artifacts/wallet-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);assert.equal(overflow,false,'Mobile document must not scroll horizontally');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: Mark Paid keeps current projects; Cashout archives only paid work, unpaid survives, revenue/cash/profit unchanged, no duplicate payment, saved cycle history and refresh, editable rates and partner shares, message retry without duplicate payout, desktop/mobile.');
})().catch(e=>{console.error(e);process.exit(1)});
