const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const filename=path.join(__dirname,'../lib/finance-notifications.ts'),mod=new Module(filename);mod.paths=module.paths;mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);const f=mod.exports;
const payment={id:'receipt-1',employeeId:'A1',name:'Person @everyone',date:'2026-09-01',gross:100000,bonus:10000,others:20000,tds:0,net:130000,lines:[{projectId:'P1',role:'Animation',gross:100000,extra:0}]};
const destination=[{Project_ID:'P1',Thread_ID:'123456789012345678'}];
function mock(status='pending'){const notice=f.paymentNotices(payment,destination)[0],job={id:notice.id,channel_id:notice.channelId,content:notice.content,status};let claims=0;const db={rpc:async()=>{if(!['pending','failed'].includes(job.status))return {data:[]};job.status='sending';claims++;return {data:[{...job}]}},from:()=>({update:values=>({eq:async()=>{Object.assign(job,values);return {error:null}}})})};return {db,job,get claims(){return claims}}}
test('receipt uses selected artist amounts and stable destination identifiers',()=>{const a=f.paymentNotices(payment,destination);assert.equal(a.length,1);assert.equal(a[0].channelId,destination[0].Thread_ID);assert.ok(a[0].content.includes('₹1,300.00'));assert.ok(a[0].content.includes('Bonus: ₹100.00'));assert.ok(!a[0].content.includes('@everyone'));assert.deepEqual(f.paymentNotices(payment,destination),a);assert.ok(a[0].id.length<=25);const bonus=f.paymentNotices({...payment,lines:[]},[],{Employee_ID:'A1',Channel_ID:'987654321012345678'});assert.equal(bonus[0].channelId,'987654321012345678');});
test('successful delivery is saved; concurrent/repeated dispatch cannot send again',async()=>{const m=mock();let sends=0;const fetcher=async(url,options)=>{sends++;const body=JSON.parse(options.body);assert.equal(body.enforce_nonce,true);assert.deepEqual(body.allowed_mentions,{parse:[]});return new Response(JSON.stringify({id:'msg-1'}),{status:200})};await Promise.all([f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher}),f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher})]);assert.equal(sends,1);assert.equal(m.job.status,'sent');assert.equal(m.job.message_id,'msg-1');});
test('definite Discord rejection stays retryable without changing payout',async()=>{const m=mock();await f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher:async()=>new Response(JSON.stringify({message:'Missing permissions'}),{status:403})});assert.equal(m.job.status,'failed');assert.match(m.job.last_error,/403/);await f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher:async()=>new Response(JSON.stringify({id:'ok'}),{status:200})});assert.equal(m.job.status,'sent');});
test('uncertain network failure is never blindly resent',async()=>{const m=mock();let sends=0;const fetcher=async()=>{sends++;throw Error('lost response')};await f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher});assert.equal(m.job.status,'unknown');await f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher});assert.equal(sends,1);});
test('Discord rate limit stores retry deadline',async()=>{const m=mock();await f.dispatchNotice(m.db,m.job.id,{token:'fake',fetcher:async()=>new Response(JSON.stringify({retry_after:30}),{status:429})});assert.equal(m.job.status,'failed');assert.ok(new Date(m.job.next_attempt_at)>new Date());});

test('delivery verification matches this bot and the exact saved receipt without posting',async()=>{const m=mock('unknown');let posts=0;const fetcher=async(url,options)=>{if(options.method==='POST')posts++;return new Response(JSON.stringify(url.endsWith('/users/@me')?{id:'our-bot'}:[{id:'wrong',author:{id:'other-bot',bot:true},content:m.job.content},{id:'right',author:{id:'our-bot',bot:true},content:m.job.content}]),{status:200})};await f.verifyNotice(m.db,m.job,{token:'fake',fetcher});assert.equal(posts,0);assert.equal(m.job.message_id,'right');assert.equal(m.job.status,'sent');});

test('project payout also gets one artist summary at invoice thread or workspace',()=>{
 const artist={Employee_ID:'A1',invoice_thread_id:'987654321012345678',Channel_ID:'111111111111111111'};
 const n=f.paymentNotices(payment,destination,artist);assert.equal(n.length,2);assert.equal(n[1].projectId,'');assert.equal(n[1].channelId,artist.invoice_thread_id);assert.match(n[1].content,/Projects: P1/);assert.match(n[1].content,/1,300.00/);
 assert.equal(f.paymentNotices(payment,destination,{...artist,invoice_thread_id:'null'})[1].channelId,artist.Channel_ID);
 assert.equal(f.paymentNotices(payment,destination,{...artist,invoice_thread_id:destination[0].Thread_ID}).length,1);
 assert.equal(f.paymentNotices(payment,destination)[0].id,n[0].id,'Existing project receipt identity stays stable');
});
test('a host without a bot token leaves the message pending for the Python worker',async()=>{
 const m=mock();let sends=0;await f.dispatchNotice(m.db,m.job.id,{token:'',fetcher:async()=>{sends++;throw Error('must not send')}});assert.equal(m.claims,0);assert.equal(m.job.status,'pending');assert.equal(sends,0);
});
