'use client'
import { Fragment, useState } from 'react'
import { adjustments, pending, payoutIssues, type Wallet, type Draft } from '@/lib/finance'
import styles from './finance-wallet.module.css'
type Line=ReturnType<typeof pending>[number]
type Employee={id:string;name:string;lines:Line[]}
type Price={key:string;amount:number}
const money=(n:number)=>(n/100).toLocaleString('en-IN',{style:'currency',currency:'INR'})
export default function FinancePayoutTable({wallet,employees,month,drafts,busy,setupRequired,pricingDirty,excluded,onExclude,onDraft,onSave,onReview}:{wallet:Wallet;employees:Employee[];month:string;drafts:Record<string,Draft>;busy:boolean;setupRequired:boolean;pricingDirty:boolean;excluded:Set<string>;onExclude:(key:string,include:boolean)=>void;onDraft:(id:string,key:keyof Draft,value:string)=>void;onSave:(rows:{employeeId:string;draft:Draft;prices:Price[]}[])=>Promise<boolean>;onReview:(id:string)=>void}) {
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[prices,setPrices]=useState<Record<string,string>>({})
 const fallback:Draft={bonus:0,others:0,tdsPercent:wallet.settings.tdsPercent,note:''}
 const draft=(id:string)=>drafts[month+':'+id]||fallback
 const price=(l:Line)=>prices[l.key]===undefined?l.gross:(prices[l.key]===''?NaN:Number(prices[l.key])*100)
 const changed=(e:Employee)=>e.lines.filter(l=>prices[l.key]!==undefined).map(l=>({key:l.key,amount:prices[l.key]===''?NaN:Number(prices[l.key])}))
 const row=(e:Employee)=>({employeeId:e.id,draft:draft(e.id),prices:changed(e)})
 const save=async(list:Employee[])=>{if(await onSave(list.map(row))){setPrices(old=>Object.fromEntries(Object.entries(old).filter(([key])=>!list.some(e=>e.lines.some(l=>l.key===key)))))}}
 const dirty=(e:Employee)=>changed(e).length>0||JSON.stringify(draft(e.id))!==JSON.stringify(wallet.drafts[month+':'+e.id]||fallback)
 return <div className={styles.panel}><div className={styles.sectionHead}><div><h2>Payout Calculator</h2><p className={styles.muted}>Approved, unpaid work only. Expand an artist to review roles, select projects and edit prices.</p></div><button disabled={busy||pricingDirty||!employees.length} onClick={()=>save(employees)}>💾 Master Save</button></div><label>Search artist<input placeholder="Search by name or ID…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className={styles.tableWrap}><table className={styles.payoutTable}><thead><tr><th>Artist / work</th><th>Minutes</th><th>Rate / fee (₹)</th><th>Gross</th><th>Bonus (₹)</th><th>Others (₹)</th><th>TDS %</th><th>Net payable</th><th>Save / pay</th></tr></thead><tbody>
 {employees.filter(e=>(e.name+' '+e.id).toLowerCase().includes(search.toLowerCase())).map(e=>{
 const d=draft(e.id),selected=e.lines.filter(l=>!excluded.has(l.key)),gross=selected.reduce((n,l)=>n+price(l),0),extras=selected.reduce((n,l)=>n+l.extra,0),earlier=adjustments(Object.fromEntries(Object.entries(wallet.drafts).filter(([k])=>k.slice(0,7)<month)),e.id,month).reduce((n,d)=>n+d.bonus+d.others,0),net=gross+extras+earlier+Math.round((d.bonus+d.others)*100)-Math.round(gross*d.tdsPercent/100)
 const leadOnly=e.lines.length>0&&e.lines.every(l=>l.role==='Lead'),rateLines=e.lines.filter(l=>leadOnly||l.role!=='Lead'),rates=[...new Set(rateLines.map(l=>leadOnly?price(l)/100:l.seconds?price(l)*60/l.seconds/100:0))]
 const roleSummary=[...new Set(e.lines.map(l=>l.role))].map(role=>e.lines.filter(l=>l.role===role).length+' '+role.toLowerCase()).join(' · ')
 const open=expanded.has(e.id)
 return <Fragment key={e.id}><tr data-employee={e.id}><td><button className={styles.artistToggle} aria-expanded={open} aria-label={'Expand '+e.name} onClick={()=>setExpanded(old=>{const next=new Set(old);next.has(e.id)?next.delete(e.id):next.add(e.id);return next})}>{open?'▾':'▸'} <strong>{e.name}</strong></button><small>{e.id} · {new Set(e.lines.map(l=>l.projectId)).size} projects</small><small>{roleSummary||'Bonus / other pay only'}</small></td><td>{(selected.reduce((n,l)=>n+l.seconds,0)/60).toFixed(2)}</td><td><input aria-label={'Rate for '+e.name} type="number" min="0" step="0.01" placeholder="Mixed" disabled={busy||!rateLines.length} value={rates.length===1&&Number.isFinite(rates[0])?Number(rates[0].toFixed(2)):''} onChange={event=>{const value=event.target.value;setPrices(old=>({...old,...Object.fromEntries(rateLines.map(l=>[l.key,value===''?'':String(leadOnly?Number(value):Math.round(l.seconds*Number(value)/60*100)/100)]))}))}}/><small>{leadOnly?'Per project lead fee':'Per minute · non-lead work'}</small></td><td>{money(gross)}</td><td><input aria-label={'Bonus for '+e.name} type="number" min="0" step="0.01" value={Number.isFinite(d.bonus)?d.bonus:''} onChange={event=>onDraft(e.id,'bonus',event.target.value)}/></td><td><input aria-label={'Other pay for '+e.name} type="number" min="0" step="0.01" value={Number.isFinite(d.others)?d.others:''} onChange={event=>onDraft(e.id,'others',event.target.value)}/>{earlier>0&&<small>Carry-forward {money(earlier)}</small>}</td><td><input aria-label={'TDS for '+e.name} type="number" min="0" max="100" step="0.01" value={Number.isFinite(d.tdsPercent)?d.tdsPercent:''} onChange={event=>onDraft(e.id,'tdsPercent',event.target.value)}/></td><td><b className={styles.netPay}>{Number.isFinite(net)?money(net):'—'}</b>{extras>0&&<small>Includes project extras {money(extras)}</small>}</td><td><div className={styles.payActions}><button disabled={busy||pricingDirty} onClick={()=>save([e])}>Save details{dirty(e)?' *':''}</button><button className={styles.primary} disabled={busy||pricingDirty||setupRequired||dirty(e)||!!d.needsReview||(!selected.length&&net<=0)||selected.some(l=>payoutIssues(l.issues).length>0)} onClick={()=>onReview(e.id)}>Mark Paid / Lock</button></div></td></tr>
 {open&&<tr><td colSpan={9}><div className={styles.payoutDetail}><label>Note / reference<input aria-label={'Note for '+e.name} value={d.note} onChange={event=>onDraft(e.id,'note',event.target.value)}/></label>{d.needsReview&&<p className={styles.warning}>Review the imported bonus and other pay, then Save details.</p>}<table><thead><tr><th>Include</th><th>Project</th><th>Role</th><th>Minutes</th><th>Project pay (₹)</th><th>Extras</th></tr></thead><tbody>{e.lines.map(l=><tr key={l.key}><td><input aria-label={'Include '+l.projectId+' '+l.role+' for '+e.name} type="checkbox" checked={!excluded.has(l.key)} onChange={event=>onExclude(l.key,event.target.checked)}/></td><td><b>{l.title}</b><small>{l.projectId} · {l.date}</small>{l.issues.map(issue=><small key={issue} className={styles.danger}>{issue}</small>)}</td><td>{l.role}</td><td>{(l.seconds/60).toFixed(2)}</td><td><input aria-label={'Price '+l.key} type="number" min="0" step="0.01" value={prices[l.key]??String(l.gross/100)} onChange={event=>setPrices(old=>({...old,[l.key]:event.target.value}))}/></td><td>{money(l.extra)}</td></tr>)}</tbody></table><p className={styles.muted}>Manual work prices stay fixed when studio rates change. Lead fees are separate from animation and lighting. Save details before Mark Paid.</p></div></td></tr>}
 </Fragment>})}
 </tbody></table></div>{!employees.length&&<p className={styles.empty}>No unpaid work in this period.</p>}</div>
}
