'use client'
import { useEffect, useState } from 'react'
import type { Wallet } from '@/lib/finance'
import styles from './finance-wallet.module.css'
type PreviousPayment={id:string;date:string;name:string;reference:string;gross:number;bonus:number;others:number;net:number;note:string;kind?:string}
const money=(value:number)=>(value/100).toLocaleString('en-IN',{style:'currency',currency:'INR'})
export default function FinancePayoutHistory(){
 const [data,setData]=useState<{wallet:Wallet;legacyPayments:PreviousPayment[]}|null>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[month,setMonth]=useState('all')
 async function load(){setError('');try{const response=await fetch('/api/finance',{cache:'no-store'}),result=await response.json();if(!response.ok)throw new Error(result.error);setData(result)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[])
 const payments=[...(data?.wallet.settlements||[]).map(s=>({id:s.id,date:s.date,name:s.name,reference:s.id,gross:s.gross,bonus:s.bonus,others:s.others,net:s.net,note:s.note,kind:'wallet',lines:s.lines})),...(data?.legacyPayments||[]).filter(p=>p.kind==='team').map(p=>({...p,kind:'earlier',lines:[]}))].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id))
 const months=[...new Set(payments.map(p=>p.date.slice(0,7)).filter(Boolean))].sort().reverse()
 const shown=payments.filter(p=>(month==='all'||p.date.startsWith(month))&&(p.name+' '+p.reference).toLowerCase().includes(search.toLowerCase()))
 return <section className={styles.wallet} aria-label="Previous artist payouts"><div className={styles.panel}><div className={styles.sectionHead}><div><h1>Previous Payouts</h1><p>Saved artist payments only. Approved or unpaid work belongs in Payout Calculator.</p></div><button onClick={load}>Refresh history</button></div>{error&&<p role="alert" className={styles.error}>{error}</p>}{!data&&!error?<p>Loading saved payment history…</p>:<><div className={styles.formGrid}><label>Search previous payouts<input placeholder="Artist name or payment reference" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Payment month<select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">All time</option>{months.map(m=><option key={m} value={m}>{m}</option>)}</select></label></div><div className={styles.metric}><span>{shown.length} saved payments</span><b>{money(shown.reduce((n,p)=>n+p.net,0))} net paid</b></div><div className={styles.tableWrap}><table><thead><tr><th>Artist / reference</th><th>Paid date</th><th>Gross</th><th>Bonus</th><th>Others</th><th>Net paid</th><th>Record</th></tr></thead><tbody>{shown.map(p=><tr key={p.kind+':'+p.id}><td><b>{p.name}</b><small>{p.reference}</small>{p.note&&<small>{p.note}</small>}{p.lines.length>0&&<details><summary>{p.lines.length} paid work items</summary>{p.lines.map(l=><small key={l.key}>{l.projectId} · {l.role} · {money(l.gross+l.extra)}</small>)}</details>}</td><td>{p.date||'Date unavailable'}</td><td>{money(p.gross)}</td><td>{money(p.bonus)}</td><td>{money(p.others)}</td><td><b className={styles.netPay}>{money(p.net)}</b></td><td><span className={styles.badge}>{p.kind==='wallet'?'Wallet receipt':'Earlier paid record'}</span></td></tr>)}</tbody></table></div>{!shown.length&&<p className={styles.empty}>No saved artist payments match this view.</p>}<p className={styles.muted}>Earlier records show the amounts originally stored, without recalculating them at today's rates. No payout can be created from this history screen.</p></>}</div></section>
}
