'use client'
import { useState } from 'react'
import { recurringCharges, today, type Wallet } from '@/lib/finance'
import styles from './finance-wallet.module.css'
const money=(n:number)=>(n/100).toLocaleString('en-IN',{style:'currency',currency:'INR'})
export default function FinanceRecurring({wallet,month,busy,onSave,onPaid}:{wallet:Wallet;month:string;busy:boolean;onSave:(rule:{id?:string;name:string;amount:number;from:string;active:boolean})=>Promise<boolean>;onPaid:(key:string)=>Promise<boolean>}) {
 const current=today().slice(0,7),[form,setForm]=useState({id:'',name:'Arun salary',amount:'15000',from:current,active:true})
 const charges=recurringCharges(wallet).filter(c=>month==='all'||c.month===month).sort((a,b)=>b.month.localeCompare(a.month))
 return <section className={styles.panel}><h2>Monthly salaries & recurring expenses</h2><p className={styles.muted}>Saved schedules count once per month in profit. Record payment separately when money is actually paid. Changing a future amount preserves earlier months.</p><form onSubmit={async e=>{e.preventDefault();if(await onSave({...form,id:form.id||undefined,amount:Number(form.amount)}))setForm({id:'',name:'',amount:'',from:current,active:true})}}><div className={styles.formGrid}><label>Expense / salary name<input required readOnly={!!form.id} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Monthly amount (₹)<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Effective month<input required type="month" min={current} value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label>Schedule<select value={form.active?'active':'paused'} onChange={e=>setForm({...form,active:e.target.value==='active'})}><option value="active">Active monthly</option><option value="paused">Pause from this month</option></select></label></div><div className={styles.actions}><button className={styles.primary} disabled={busy}>Save monthly expense</button>{form.id&&<button type="button" onClick={()=>setForm({id:'',name:'',amount:'',from:current,active:true})}>Cancel edit</button>}</div></form>
 {(wallet.recurringExpenses||[]).map(rule=>{const next=[...rule.versions].sort((a,b)=>a.from.localeCompare(b.from)).at(-1)!;return <div className={styles.metric} key={rule.id}><span><b>{rule.name}</b><small> · {money(next.amount)} / month · {next.active?'Active':'Paused'} from {next.from}</small></span><button disabled={busy} onClick={()=>setForm({id:rule.id,name:rule.name,amount:String(next.amount/100),from:next.from>current?next.from:current,active:next.active})}>Edit schedule</button></div>})}
 {!!charges.length&&<><h3 style={{marginTop:24}}>Monthly expense history</h3><div className={styles.tableWrap}><table><thead><tr><th>Month</th><th>Expense</th><th>Cost in profit</th><th>Payment</th></tr></thead><tbody>{charges.map(c=><tr key={c.key}><td>{c.month}</td><td>{c.name}</td><td>{money(c.amount)}</td><td>{c.paid?<span className={styles.badge}>Payment recorded</span>:<button disabled={busy} onClick={()=>{if(window.confirm('Record '+money(c.amount)+' actually paid for '+c.name+' / '+c.month+'?'))void onPaid(c.key)}}>Record expense paid</button>}</td></tr>)}</tbody></table></div></>}
 </section>
}
